katalog/urls.py
from django.urls import path
from katalog.views import show_katalog


app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
    
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import logout_user #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import create_task #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import task_toggle #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import task_delete #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import show_todolist_ajax
from todolist.views import add_todolist_ajax
from todolist.views import show_json #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import show_json_by_id #sesuaikan dengan nama fungsi yang dibuat

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('ajax/', show_todolist_ajax, name='show_todolist_ajax'),
    path("ajax/submit/", add_todolist_ajax, name="add_todolist_ajax"),
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat
    path('create-task/', create_task, name='create_task'),
    path('toggle-task/<int:id>', task_toggle, name='toggle_task'),
    path('delete-task/<int:id>', task_delete, name='delete_task'),
    path('json/', show_json, name='show_json'), #sesuaikan dengan nama fungsi yang dibuat
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), #sesuaikan dengan nama fungsi yang dibuat
]

todolist/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class CreateForm(forms.Form):
    title = forms.CharField(label = "Title")
    description = forms.CharField(label = "Description")

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.models import Task
from .forms import CreateForm
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.http import HttpResponse
from django.core import serializers

# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist_item = Task.objects.filter(user= request.user)
    context = {
    'list_item': todolist_item  ,
    'name': 'Irsyad Mufid',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    todolist_item = Task.objects.filter(user= request.user)
    context = {
    'name': 'Irsyad Mufid',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "todolist_ajax.html",context)



def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context) 

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)   


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response


def create_task(request):  
    context = {}
    if request.method == "POST":
        form = CreateForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            Task.objects.create(title = title, description = description, date = datetime.datetime.now(), user = request.user)
            return redirect('todolist:show_todolist')
    else: 
        form = CreateForm()

    context = {
        'form' : form,
        }
    return render(request, "create-task.html", context)

@csrf_exempt
@login_required(login_url="/todolist/login/")
def add_todolist_ajax(request):
    if request.method == "POST":
        title = request.POST.get("title")
        print(title)
        description = request.POST.get("description")
        item = Task.objects.create(title = title, description = description, date = datetime.datetime.now(), user = request.user)
        item.save()
        JsonResponse({"instance": "Proyek Dibuat"}, status=200)
    return redirect("todolist:show_todolist_ajax")


def task_toggle(request, id):
    task = Task.objects.get(id=id)
    if task.is_finished:
        task.is_finished = False
    else:
        task.is_finished = True
    task.save()
    return redirect('todolist:show_todolist')

def task_delete(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return show_todolist(request)

def show_json(request):
    data = Task.objects.filter(user= request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    
def show_json_by_id(requst, id):
    data = Task.objects.filter(user= request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/templates/login.html
{% extends 'base.html' %}

{% block content %}


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<div class="bg-image" 
    style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.jpg');
            height: 100vh">
<form method="POST" action="">
{% csrf_token %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your login and password!</p>

              <div class="form-outline form-white mb-4">
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                <label class="form-label" for="typeEmailX">Username</label>
              </div>

              <div class="form-outline form-white mb-4">
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                <label class="form-label" for="typePasswordX">Password</label>
              </div>
              <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
            <div>
              <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-white-50 fw-bold">Sign Up</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
<style>
    body {
        margin: 0;
        background-image: url('https://wallpaperaccess.com/full/84248.png');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        }
    </style>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}


<!-- <style>
h1, h5, p {text-align: center; color: rgb(255,253,253);font-size:2vw;}
th {text-align: center;}
tr {background-color: rgb(237,255,89);}
div {text-align: center;}


table, th, td {
border: 1px solid rgb(255, 180, 89);
table-layout: fixed;
text-align: center;
word-break: break-all
}
table {
margin-left: auto;
margin-right: auto;
width: 100%;
}
body {
margin: 0;
background-image: url('https://htmlcolorcodes.com/assets/images/html-color-codes-color-tutorials.jpg');
background-repeat: no-repeat;
background-attachment: fixed;
background-size: 100% 100%;
}
</style> -->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<div class="bg-image" 
     style="background-image: url('https://wallpaperaccess.com/full/19276.jpg');
            height: 100vh;
            background-repeat: no-repeat;
            background-size: 100% 100%;
            ">


<nav class="navbar navbar-expand-lg navbar-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarCenteredExample"
      aria-controls="navbarCenteredExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div
      class="collapse navbar-collapse justify-content-center"
      id="navbarCenteredExample"
    >
      <!-- Left links -->
      <span class="navbar-text"
          style="color: #fafafa">
          {{ user.get_username }}
        </span>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" style="color: #fafafa" href="#">todolist</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color: #fafafa" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
        <!-- Navbar dropdown -->
        <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            style="color: #fafafa"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            Dropdown
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="#">Action</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another action</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
  
          </ul>
        </li>
        </ul>
        <li class="nav-item">
          <a class="nav-link" style="color: #fafafa" href="{% url 'todolist:create_task' %}">Tambah Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color: #fafafa" href="{% url 'todolist:show_todolist_ajax' %}">Ajax</a>
        </li>
        
        <li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>



<div class="d-flex align-items-center">
<div class="d-inline-block">
<span class="container">
<div class="my-auto mx-auto">
<div class="card " style="width: 12rem;">
  {% for task in list_item %}
  <h5 class="card-header d-flex justify-content-between align-items-center">
    Task : {{task.title}}
    </h5>
  <div class="card-body">
    <p class="card-text">Date : {{task.date}}</p>
    <p class="card-text">
      Description : {{task.description}}</p>
    <p class="card-text">
      Status : 
      {% if task.is_finished %}
      Finished
      {% else %}
      Not Yet
      {% endif %}
    </p>
                
  </div>
  {% endfor %} 
</div>
</div>
</span>
</div>

<div class="d-inline-block">
<span class="m-5 d-flex flex-column justify-content-center align-items-center">
<!-- <h1>To-Do List</h1> -->
<p class="h1"
  style="color: #fafafa">To-Do List</p>
  



  <div class="m-5 d-flex flex-column justify-content-center align-items-center">
      <div class="mask d-flex align-items-center h-100">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-12">
              <div class="table-responsive card">
                  <div class="bg-image h-100" style="background-color: #ffb97f;">
                    <table class="table table-hover table-striped mb-0">
                    <thead style="background-color: #fd7601;">
                    <tr class="text-uppercase text-success">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Status</th>
                        <th scope="col">Toggle</th>
                        <th scope="col">Remove Task</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for task in list_item %}
                    <tr>
                        <th>{{ task.date }}</th>
                        <th>{{ task.title }}</th>
                        <th>{{ task.description }}</th>
                        
                        {% if task.is_finished %} 
                            <th>Selesai</th>
                            {% else %}
                            <th>Belum Selesai</th>
                            {% endif %}
                            <td>
                            <!-- <button><a href="{% url 'todolist:toggle_task' task.id %}">Check</a></button></td> -->
                            <button type="button" class="btn btn-warning btn-rounded">
                              <a href="{% url 'todolist:toggle_task' task.id %}">Toggle
                            </button>
                          </td>
                            <td>
                              <button type="button" class="btn btn-warning btn-rounded">
                                <a href="{% url 'todolist:delete_task' task.id %}">Delete
                              </button>
                            </td>
                        </tr>
                    {% endfor %}    
                    </tbody>
                </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
    <p class="h5"
    style="color: #fafafa">
    Sesi terakhir login: {{ last_login }}</p>
    </div>


 


</span>

</div>
</div>
{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block content %}


<!-- <style>
h1, h5, p {text-align: center; color: rgb(255,253,253);font-size:2vw;}
th {text-align: center;}
tr {background-color: rgb(237,255,89);}
div {text-align: center;}


table, th, td {
border: 1px solid rgb(255, 180, 89);
table-layout: fixed;
text-align: center;
word-break: break-all
}
table {
margin-left: auto;
margin-right: auto;
width: 100%;
}
body {
margin: 0;
background-image: url('https://htmlcolorcodes.com/assets/images/html-color-codes-color-tutorials.jpg');
background-repeat: no-repeat;
background-attachment: fixed;
background-size: 100% 100%;
}-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<div class="bg-image" 
     style="background-image: url('https://wallpaperaccess.com/full/19276.jpg');
            height: 100vh;
            background-repeat: no-repeat;
            background-size: 100% 100%;
            ">

<script>
    

    function loadData(){
        $('#task_card').empty();
        $('#table_card').empty();
        let data_card ="";
        let table_card ="";
        $.ajax({
            url: "{% url 'todolist:show_json' %}",
            type: "GET",
            dataType: "json",
            success: function(data){
                for (let i of data){
                    let status = i.fields.status ? "Selesai" : "Belum Selesai";
                    data_card +=`
                   
                              <h5 class="card-header d-flex justify-content-between align-items-center" >
                                Task : ${i.fields.title}
                                </h5>
                              <div class="card-body" >
                                <p class="card-text">Date : ${i.fields.date}</p>
                                            <p class="card-text">
                                              Description : ${i.fields.description}</p>
                                            <p class="card-text">
                                              Status : ${status}
                                            
                              </div>
                            
                    `
                    ;
                }
                $('.task_card').append(data_card);
                
            },
            error: function(data){
                console.log('Error?');
            }
        })
        $.ajax({
            url: "{% url 'todolist:show_json' %}",
            type: "GET",
            dataType: "json",
            success: function(data){
              for (let i of data){
                    let status = i.fields.is_finished? "Selesai" : "Belum Selesai";
                    table_card +=`
                    <tr id="${i.id}" >
                        <th>${i.fields.date}</th>
                        <th>${i.fields.title}</th>
                        <th>${i.fields.description}</th>
                        <th>${status}</th>
                            <td>
                            
                            <button type="button" class="btn btn-warning btn-rounded"
                            <a href="todolist/toggle-task/${i.id}"> Toggle
                            </button>
                          </td>
                            <td>
                              <button type="button" class="btn btn-warning btn-rounded"
                              onclick="deleteTask(${i.id})"> Delete
                              </button>
                            </td>
                        </tr>  

                    `
                    ;
                          }
              $('.table_card').append(table_card);
            },
            error: function(data){
                console.log('Error?');
            }
        })
    }
    $(document).ready(function () {
      $("#myModal").modal();
      loadData();
    });

      $(document).on('submit', '#todolist_form',function(e){
        e.preventDefault();
        var title=$("#title").val(); 
        var description=$("#description").val(); 
        var csrf_token = $('input[name=csrfmiddlewaretoken]').val();
        $.ajax({
            type:'POST',
            url: "{% url 'todolist:add_todolist_ajax' %}",
            data:{
                title:title,
                description:description,
                csrfmiddlewaretoken:csrf_token,
                action: 'post'
            },
            success:function(){
                document.getElementById("todolist_form").reset();
                loadData();
            },
        });
    });
    function deleteTask(val){
        console.log();
        $.ajax({
            url :`/todolist/delete-task/${id}`,
            success: function () {
                console.log();
                $(`#${id}`).remove()
            },
        })
    }

</script>

<nav class="navbar navbar-expand-lg navbar-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarCenteredExample"
      aria-controls="navbarCenteredExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div
      class="collapse navbar-collapse justify-content-center"
      id="navbarCenteredExample"
    >
      <!-- Left links -->
      <span class="navbar-text"
      style="color: #fafafa">
      {{ user.get_username }}
    </span>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" style="color: #fafafa" href="#">Todolist Ajax</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color: #fafafa" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
        <!-- Navbar dropdown -->
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            style="color: #fafafa"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            Dropdown
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="#">Action</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another action</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link" style="color: #fafafa" href="{% url 'todolist:create_task' %}">Tambah Task</a> -->
          <a class="nav-link" style="color: #fafafa" data-toggle="modal" data-target="#myModal" href="#" >Tambah Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color: #fafafa" href="{% url 'todolist:show_todolist' %}">Todolist</a>
        </li>
        
       
        <li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>



<div class="d-flex align-items-center" >
<div class="d-inline-block">
<span class="container">
<div class="my-auto mx-auto">
<div class="card " style="width: 12rem;"  >
<div class="task_card"  id ="task_card"  >
 
</div>          
</div>
</div>
</span>
</div>


<div class="d-inline-block">
<span class="m-5 d-flex flex-column justify-content-center align-items-center">
<!-- <h1>To-Do List</h1> -->
<p class="h1"
  style="color: #fafafa">To-Do List</p>
  <div class="m-5 d-flex flex-column justify-content-center align-items-center">
      <div class="mask d-flex align-items-center h-100">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-12">
            
              <div class="table-responsive card" >
                  <div class="bg-image h-100" style="background-color: #ffb97f;">
                    <table class="table table-hover table-striped mb-0"  >
                      <thead style="background-color: #fd7601;">
                      <tr class="text-uppercase text-success">
                      <tr>
                          <th scope="col">Date</th>
                          <th scope="col">Title</th>
                          <th scope="col">Description</th>
                          <th scope="col">Status</th>
                          <th scope="col">Toggle</th>
                          <th scope="col">Remove Task</th>
                      </tr>
                      </thead>
                      <tbody class ="table_card" id="table_card">

                      </tbody>
                      </table>
            </div>
          </div>
          </div>

      </div>
    </div>
    </div>
    <p class="p"
    style="color: #fafafa">
    Sesi terakhir login: {{ last_login }}</p>
    </div>
</span>

</div>


<div class="d-inline-block">
  
    <span class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content rounded-0">
          <div class="modal-body py-0">
            <div class="d-flex main-content">
              <div class="content-text p-4">
                <h5>Tambah Task</h5>

                <form method="post" id="todolist_form">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="title" class="form-label">Title</label>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Masukkan nama barang"
                      name="title"
                      id="title"
                    />
                  </div>
                  <div class="form-group">
                  <label for="description" class="form-label">description</label>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Masukkan description barang"
                    name="description"
                    id="description"
                  />
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
              </div>
            

          </div>
        </div>
      </span>
</div>

</div>

</div>

</div>
{% endblock content %}